version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "2000:2000"
      - "2443:2443"
    environment:
      - NODE_ENV=docker
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
    stdin_open: true
    restart: always
